name: Verify & Release
on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited
      - closed
  push:
    branches:
      - '*'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  GOPROXY: https://proxy.golang.org

permissions:
    contents: write
    packages: read
    statuses: write
    pull-requests: write

jobs:             
    verify_quality:
      name: Verify Code Quality
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-go@v5
          with:
            go-version: '1.23'

        - name: golangci-lint
          uses: golangci/golangci-lint-action@v4
          with:
            version: v1.56.2
            working-directory: ./
            only-new-issues: false
            args: --concurrency=16 --timeout=5m --out-format=github-actions --issues-exit-code=1
            skip-cache: false
            skip-pkg-cache: true

    # Add Golang Tests when they will be available
    verify_functionality:
      name: Verify Code Functionality
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-go@v5
          with:
            go-version: '1.23'

        - name: execute funtional tests
          run: go test ./...